"""SMILES -> 3D conformer ensemble for an analogue, with honest failure.

Mirrors what a campaign's reference-ensemble generator does for the parent (ETKDGv3 +
MMFF94 optimization + heavy-atom RMSD dedup) so that analogue conformers and
the parent's committed ensemble are generated by the SAME procedure. A fit
comparison between a parent ensemble built one way and analogue ensembles built
another would confound the modification with the conformer-generation method.

Failure is explicit: embedding can fail (strained ring systems, bad valences),
MMFF can fail to type an atom, and an analogue that produces zero usable
conformers must be reported as such rather than silently contributing nothing to
a ranking.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .design import Analogue


@dataclass
class EmbeddedAnalogue:
    """3D conformers for one analogue, plus everything needed to trace them.

    `error` non-None means no usable geometry: the analogue must appear in
    reports as UNEVALUATED, never as a zero/neutral score.
    """

    analogue: Analogue
    symbols: list[str] = field(default_factory=list)
    # One (natoms, 3) list-of-tuples per conformer, in Angstrom.
    conformers: list[list[tuple[float, float, float]]] = field(default_factory=list)
    mmff_energies: list[float] = field(default_factory=list)  # kcal/mol
    pharmacophore: dict[str, bool] = field(default_factory=dict)
    # Net charge of the embedded species, copied from the Analogue so a consumer
    # cannot pair these coordinates with the wrong electron count.
    net_charge: int = 0
    error: str | None = None
    # Set when RMSD deduplication had to be skipped: the conformers are still
    # usable and energy-ordered, but may contain near-duplicates, so any claim
    # about conformational DIVERSITY must check this first.
    dedup_note: str | None = None

    @property
    def n_conformers(self) -> int:
        return len(self.conformers)

    @property
    def usable(self) -> bool:
        return self.error is None and self.n_conformers > 0

    @property
    def best_index(self) -> int | None:
        """Index of the lowest-MMFF-energy conformer, or None if unusable."""
        if not self.usable or not self.mmff_energies:
            return None
        return min(range(len(self.mmff_energies)), key=lambda i: self.mmff_energies[i])

    def write_xyz(self, out_dir: str | Path, prefix: str | None = None) -> list[Path]:
        """Write each conformer as an xyz, returning the paths (in order).

        Written in the same layout a campaign fetch script uses so
        a ligand reader can consume them unchanged.
        """
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        prefix = prefix or self.analogue.label
        paths = []
        for i, coords in enumerate(self.conformers):
            # The header below is `len(self.symbols)` while the body comes from
            # `zip(self.symbols, coords)`, which stops at the shorter one. A
            # mismatch therefore writes a file whose header disagrees with its
            # contents, and it reads back as a different molecule.
            if len(coords) != len(self.symbols):
                raise ValueError(
                    f"conformer {i} has {len(coords)} coordinates for "
                    f"{len(self.symbols)} symbols -- these are per-atom and "
                    f"must match, or the xyz header will disagree with its body"
                )
            p = out_dir / f"{prefix}_conf_{i:02d}.xyz"
            lines = [
                str(len(self.symbols)),
                f"{self.analogue.label} conf {i} "
                f"mmff={self.mmff_energies[i]:.4f}kcal/mol",
            ]
            for sym, (x, y, z) in zip(self.symbols, coords):
                lines.append(f"{sym:<3s} {x:14.8f} {y:14.8f} {z:14.8f}")
            p.write_text("\n".join(lines) + "\n")
            paths.append(p)
        return paths


def embed_analogue(
    analogue: Analogue,
    n_conformers: int = 20,
    rmsd_threshold: float = 0.5,
    random_seed: int = 0xF00D,
    max_attempts_multiplier: int = 4,
) -> EmbeddedAnalogue:
    """Generate, MMFF-optimize and dedupe conformers for one analogue.

    `random_seed` is fixed by default so a campaign is reproducible: ETKDG is
    stochastic, and an unseeded run would make analogue rankings irreproducible
    for reasons unrelated to chemistry.
    """
    from rdkit import Chem
    from rdkit.Chem import AllChem, rdMolAlign

    result = EmbeddedAnalogue(analogue=analogue, net_charge=analogue.net_charge)

    # Embed the SCORING species -- the ionized form when one is declared. The
    # anion's geometry differs from the neutral acid's (a carboxylate is
    # symmetric and planar; a COOH is not), and the anion is the species that
    # exists at pH 7.4, so embedding the neutral form and scoring it as an anion
    # would be inconsistent in both geometry and electron count.
    mol = Chem.MolFromSmiles(analogue.scoring_smiles)
    if mol is None:
        result.error = f"unparseable scoring SMILES: {analogue.scoring_smiles}"
        return result

    try:
        result.pharmacophore = analogue.pharmacophore.check(mol)
    except ValueError as e:
        result.error = f"pharmacophore spec error: {e}"
        return result

    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = random_seed
    params.pruneRmsThresh = rmsd_threshold
    params.useSmallRingTorsions = True  # strained small rings need this

    # ETKDGv3 runs its own minimization internally, which can abort with an
    # RDKit "Invariant Violation" (a RuntimeError out of BFGSOpt) on
    # over-constrained cages -- so the embedding call needs the same guard as
    # the MMFF stage below. Discovered by
    # tests/test_embed.py::test_impossible_geometry_is_reported_as_unevaluated,
    # which is exactly the failure path it exists to exercise.
    try:
        cids = AllChem.EmbedMultipleConfs(
            mol, numConfs=n_conformers * max_attempts_multiplier, params=params
        )
    except Exception as e:  # noqa: BLE001 - RDKit raises RuntimeError here
        result.error = (
            f"ETKDGv3 embedding aborted ({type(e).__name__}: "
            f"{str(e).splitlines()[0] if str(e) else 'no message'}). This "
            "analogue is UNEVALUATED, not low-scoring."
        )
        return result

    if len(cids) == 0:
        result.error = (
            "ETKDGv3 produced no conformers (strained or invalid geometry). "
            "This analogue is UNEVALUATED, not low-scoring."
        )
        return result

    # MMFF94 optimize. A typing failure is not fatal to the whole analogue --
    # fall back to the unoptimized embedding but SAY SO, since unoptimized
    # geometries are not comparable to optimized ones on energy.
    energies: dict[int, float] = {}
    try:
        props = AllChem.MMFFGetMoleculeProperties(mol)
        if props is None:
            raise ValueError("MMFFGetMoleculeProperties returned None (untypable atom)")
        opt = AllChem.MMFFOptimizeMoleculeConfs(mol, maxIters=2000)
        for cid, (converged, energy) in zip(cids, opt):
            # converged == 0 means the optimization converged (RDKit convention:
            # nonzero means it hit maxIters). Keep the non-converged ones but
            # they are the first to be dropped by the energy window.
            energies[int(cid)] = float(energy)
    except Exception as e:  # noqa: BLE001
        result.error = (
            f"MMFF94 optimization unavailable ({type(e).__name__}: {e}); "
            "geometries would not be energy-comparable to the rest of the set, "
            "so this analogue is reported UNEVALUATED rather than scored on "
            "unoptimized coordinates."
        )
        return result

    # Deduplicate on heavy-atom best-fit RMSD, keeping the lower-energy member of
    # each pair -- pruneRmsThresh acts on the pre-optimization embedding, so
    # optimization can collapse distinct starts onto the same minimum.
    heavy = Chem.RemoveHs(mol)
    order = sorted(energies, key=lambda c: energies[c])
    kept: list[int] = []
    try:
        for cid in order:
            if all(
                rdMolAlign.GetBestRMS(heavy, heavy, prbId=cid, refId=k) > rmsd_threshold
                for k in kept
            ):
                kept.append(cid)
            if len(kept) >= n_conformers:
                break
    except Exception as e:  # noqa: BLE001 - substructure-match blowup on cages
        # Dedup failing is not a reason to discard good geometry: fall back to
        # energy order without RMSD pruning, and record that we did. Silently
        # returning a possibly-redundant ensemble would misreport conformational
        # diversity, so the note travels with the result.
        kept = order[:n_conformers]
        result.error = None
        result.dedup_note = (
            f"RMSD dedup skipped ({type(e).__name__}: "
            f"{str(e).splitlines()[0] if str(e) else 'no message'}); conformers "
            "are energy-ordered but may include near-duplicates."
        )

    result.symbols = [a.GetSymbol() for a in mol.GetAtoms()]
    for cid in kept:
        conf = mol.GetConformer(cid)
        result.conformers.append(
            [tuple(conf.GetAtomPosition(i)) for i in range(mol.GetNumAtoms())]
        )
        result.mmff_energies.append(energies[cid])
    return result
